name: Update GitHub Stats

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Checkout generator repo
        uses: actions/checkout@v4
        with:
          repository: yogeshwaran01/github-stats-terminal-style
          path: generator

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install & Build
        run: |
          cd generator
          npm install
          npm run build
          # Генерация SVG (создается внутри папки generator)
          node dist/bin/github-stats-terminal.js ${{ github.repository_owner }} atom
          # Перемещаем файл в корень твоего репозитория
          mv github_stats.svg ../github_stats.svg
        env:
          GHT: ${{ secrets.GHT }}

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add github_stats.svg
          git commit -m "Update GitHub Stats" || exit 0
          git push origin main
